import type { Metadata } from "next";
import { Exo} from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "./_Component/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner"
import WrapperCom from "./_Component/WrapperCom";
import TanStackProviders from "@/Providers/TanStackProvider";
import { WishlistProvider } from "./context/WishlistContext";
import Footer from "./_Component/Footer/Footer";



const exo = Exo({
  subsets: ["latin"],
  weight:['400','500']
});

export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={exo.className}
    >
      <body>
        <>
        {/* Navbar  */}
         <TanStackProviders>
        <div className="fixed top-0 left-0 w-full z-50 bg-white max-w-screen-xl mx-auto">
          
          <WrapperCom>
            <NavigationMenuDemo/>
          </WrapperCom>
          
        </div>

        <div className="container mx-auto px-4 mt-25 max-w-screen-xl">
          <WishlistProvider>
             {children}
             <Toaster/>
          </WishlistProvider>
        </div>
        </TanStackProviders>

        <Footer/>
       
        </>
        </body>
    </html>
  );
}
